CREATE TABLE CATEGORY {
	CATEGORY_ID INT AUTO_INCREMENT,
	CATEGORY_NAME VARCHAR(256) NOT NULL,
	ISSUE_LIST_ORDER TEXT,
	REGISTERED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
}

ALTER TABLE CATEGORY ADD CONSTRAINT IDX_CATEGORY_PK PRIMARY KEY (CATEGORY_ID);
ALTER TABLE CATEGORY ADD CONSTRAINT IDX_CATEGORY_UNI UNIQUE (CATEGORY_ORDER);
COMMENT ON TABLE CATEGORY IS 'The table where a side in issue is maintained.';
COMMENT ON COLUMN CATEGORY.CATEGORY_ID IS 'category id. auto increment.';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS 'category name. (e.g. TODO, DOING, DONE)';
COMMENT ON COLUMN CATEGORY.ISSUE_LIST_ORDER IS 'A side in issue is maintained as arrangement. (e.g. {1,2,3})';
COMMENT ON COLUMN CATEGORY.REGISTERED_DATE IS 'The registration date and time.';
COMMENT ON COLUMN CATEGORY.UPDATED_DATE IS 'The time of a renewal date.';



CREATE TABLE ISSUE_CATEGORY {
	ID INT AUTO_INCREMENT,
	ISSUE_ID INT NOT NULL,
	CATEGORY_ID INT NOT NULL,
	REGISTERED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
}

ALTER TABLE ISSUE_CATEGORY ADD CONSTRAINT IDX_ISSUE_CATEGORY_PK PRIMARY KEY (ID);
ALTER TABLE ISSUE_CATEGORY ADD CONSTRAINT IDX_ISSUE_CATEGORY_UNI UNIQUE (ISSUE_ID, CATEGORY_ID);
COMMENT ON TABLE ISSUE_CATEGORY IS 'The table where it''s managed which category issue belongs to.';
COMMENT ON COLUMN ISSUE_CATEGORY.ID IS 'id. auto increment.';
COMMENT ON COLUMN ISSUE_CATEGORY.ISSUE_ID IS 'The ID for the issue table.';
COMMENT ON COLUMN ISSUE_CATEGORY.CATEGORY_ID IS 'The ID for the category table.';
COMMENT ON COLUMN ISSUE_CATEGORY.REGISTERED_DATE IS 'The registration date and time.';
COMMENT ON COLUMN ISSUE_CATEGORY.UPDATED_DATE IS 'The time of a renewal date.';



